#config file
#Mon Sep 11 18:20:19 CST 2023

G1_POINT=HkYtAdGGH37kmb9wqxKt4zXZhYa1LbhH7i7B55AXDgQUvYB/TmSQSynodP2CT/FuRltXmLGar+DK5gotvPkTMw\=\=
H_POINT=EdN8VxXOO3U9/yeY5eBEJaghzanV+/R2vqaNwS7RWUEengBS+gsWJPbFmFkpxl/JV0tzHOd8brvw1g4DUmR8ww83Lpn3u1AJ1/BKUfMU1/hSAIlIiOnx7CoXG2mB6JBlFoCkeS3D7oqEfh3YWO2wLVt2qgZ2GwlcHpi5wwiITvM\=
